language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

# blocklist
branches:
  except:
  - dev

sudo: false

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c ./phpunit.xml.dist

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script: PHP_VERSION=7.0.1 vendor/bin/phpunit

notifications:
    on_success: never
    on_failure: always

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
