language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
  - hhvm-nightly

sudo: false

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c ./phpunit.xml.dist

matrix:
  allow_failures:
    - rust: nightly
    - rust: hhvm
    - rust: hhvm-nightly
  fast_finish: true
  include:
    - php: hhvm
      env: PHP_VERSION=7.0.1

script: PHP_VERSION=7.0.1 vendor/bin/phpunit

notifications:
    on_success: never
    on_failure: always

after_success:
  - travis_retry php vendor/bin/coveralls
